version: '3.8'

services:
  # Banco de Dados MySQL
  mysql:
    image: mysql:8.0
    container_name: crm-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-protecar_crm}
      MYSQL_USER: ${DB_USER:-protecar}
      MYSQL_PASSWORD: ${DB_PASSWORD:-protecar123}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root123}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - crm-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-root123}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crm-backend
    restart: unless-stopped
    environment:
      PORT: ${PORT:-3001}
      NODE_ENV: ${NODE_ENV:-production}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-protecar_crm}
      DB_USER: ${DB_USER:-protecar}
      DB_PASSWORD: ${DB_PASSWORD:-protecar123}
      DATABASE_URL: mysql://${DB_USER:-protecar}:${DB_PASSWORD:-protecar123}@mysql:3306/${DB_NAME:-protecar_crm}
      JWT_SECRET: ${JWT_SECRET:-change-this-secret-key-in-production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      FRONTEND_URL: ${FRONTEND_URL:-http://185.217.125.72:3000}
    ports:
      - "${PORT:-3001}:3001"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - crm-network

  # Frontend Next.js
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://185.217.125.72:3001/api}
        NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL:-http://185.217.125.72:3001}
    container_name: crm-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - crm-network

volumes:
  mysql_data:
    driver: local

networks:
  crm-network:
    driver: bridge
